config/routes.rb
Rails.application.routes.draw do

  resources :issues

  resources :projects

  resources :teams

  resources :tlitems

  resource :tasks do
    collection do
      get :getoutlist
    end
  end

  resources :todolists do
    member do
      get :addtasks
    end
    collection do
      post :getbydate
      get 'findbydate/:date' => :findbydate, :as => 'findbydate'
    end
  end

  devise_for :users, :controllers => {:registrations => "users/registrations", sessions: "users/sessions"}

  root 'home#index'

  get 'account' => 'account#index'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/issue.rb
class Issue < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base	
  has_many :tlitem
  enum status: [ :inlist, :pending, :finished, :outlist ]
  enum task_type: [ :shared, :personal ]
  scope :outlist, -> { where(status: 3) }
end

app/models/tbitem.rb
class Tbitem < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
end

app/models/tlitem.rb
class Tlitem < ActiveRecord::Base
	belongs_to :task
  belongs_to :todolist
  scope :with_task, -> { joins(:task).select('tlitems.id as tlitem_id, tasks.id as task_id, title') }
end

app/models/todolist.rb
class Todolist < ActiveRecord::Base
	belongs_to :user
  has_many :tlitems
  has_and_belongs_to_many :tasks, :join_table => :tlitems
	enum result: [ :good, :regular, :bad ]
  enum status: [ :inprogress, :finished ]
end

app/models/token.rb
class Token < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :todolists
  has_many :tasks
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :avatar, :attachment_presence => true
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :avatar, :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index    
    gon.todolisturl = getbydate_todolists_path
    gon.todolisfindbydate = findbydate_todolists_path('select-date')
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:title, :status, :rank)
    end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tlitems_helper.rb
module TlitemsHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.number_field :rank %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Issues</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Status</th>
      <th>Rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.title %></td>
        <td><%= issue.status %></td>
        <td><%= issue.rank %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @issue.title %>
</p>

<p>
  <strong>Status:</strong>
  <%= @issue.status %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @issue.rank %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>