config/routes.rb
Rails.application.routes.draw do

  resources :issues

  resources :projects

  resources :teams

  resources :tlitems

  resource :tasks do
    collection do
      get :getoutlist
    end
  end

  resources :todolists do
    member do
      get :addtasks
    end
    collection do
      post :getbydate
      get 'findbydate/:date' => :findbydate, :as => 'findbydate'
    end
  end

  devise_for :users, :controllers => {:registrations => "users/registrations", sessions: "users/sessions"}

  root 'home#index'

  get 'account' => 'account#index'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/issue.rb
class Issue < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base	
  has_many :tlitem
  enum status: [ :inlist, :pending, :finished, :outlist ]
  enum task_type: [ :shared, :personal ]
  scope :outlist, -> { where(status: 3) }
end

app/models/tbitem.rb
class Tbitem < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
end

app/models/tlitem.rb
class Tlitem < ActiveRecord::Base
	belongs_to :task
  belongs_to :todolist
  scope :with_task, -> { joins(:task).select('tlitems.id as tlitem_id, tasks.id as task_id, title') }
end

app/models/todolist.rb
class Todolist < ActiveRecord::Base
	belongs_to :user
  has_many :tlitems
  has_and_belongs_to_many :tasks, :join_table => :tlitems
	enum result: [ :good, :regular, :bad ]
  enum status: [ :inprogress, :finished ]
end

app/models/token.rb
class Token < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :todolists
  has_many :tasks
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :avatar, :attachment_presence => true
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :avatar, :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index    
    gon.todolisturl = getbydate_todolists_path
    gon.todolisfindbydate = findbydate_todolists_path('select-date')
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Custom #

  def getoutlist
    @tasks = current_user.tasks.outlist
    render json: @tasks
  end

  # End Custom #

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :rank)
    end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tlitems_helper.rb
module TlitemsHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.number_field :rank %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.date %></td>
        <td><%= task.rank %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @task.date %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @task.rank %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>