config/routes.rb
Rails.application.routes.draw do

  resources :issues

  resources :projects

  resources :teams

  resources :tlitems

  resource :tasks do
    collection do
      get :getoutlist
    end
  end

  resources :todolists do
    member do
      get :addtasks
    end
    collection do
      post :getbydate
      get 'findbydate/:date' => :findbydate, :as => 'findbydate'
    end
  end

  devise_for :users, :controllers => {:registrations => "users/registrations", sessions: "users/sessions"}

  root 'home#index'

  get 'account' => 'account#index'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/issue.rb
class Issue < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base	
  has_many :tlitem
  enum status: [ :inlist, :pending, :finished, :outlist ]
  enum task_type: [ :shared, :personal ]
  scope :outlist, -> { where(status: 3) }
end

app/models/tbitem.rb
class Tbitem < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
end

app/models/tlitem.rb
class Tlitem < ActiveRecord::Base
	belongs_to :task
  belongs_to :todolist
  scope :with_task, -> { joins(:task).select('tlitems.id as tlitem_id, tasks.id as task_id, title') }
end

app/models/todolist.rb
class Todolist < ActiveRecord::Base
	belongs_to :user
  has_many :tlitems
  has_and_belongs_to_many :tasks, :join_table => :tlitems
	enum result: [ :good, :regular, :bad ]
  enum status: [ :inprogress, :finished ]
end

app/models/token.rb
class Token < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :todolists
  has_many :tasks
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :avatar, :attachment_presence => true
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :avatar, :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index    
    gon.todolisturl = getbydate_todolists_path
    gon.todolisfindbydate = findbydate_todolists_path('select-date')
  end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  before_action :set_todolist, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except: :getbydate

  # GET /todolists
  # GET /todolists.json
  def index
    @todolists = Todolist.all
  end

  # GET /todolists/1
  # GET /todolists/1.json
  def show
  end

  # GET /todolists/new
  def new
    @todolist = Todolist.new
  end

  # GET /todolists/1/edit
  def edit
  end

  # POST /todolists
  # POST /todolists.json
  def create
    @todolist = current_user.todolists.new(todolist_params)

    if @todolist.save
        redirect_to addtasks_todolist_path(@todolist.id) and return
    else
        render json: @todolist.errors
    end
  end

  # PATCH/PUT /todolists/1
  # PATCH/PUT /todolists/1.json
  def update
    respond_to do |format|
      if @todolist.update(todolist_params)
        format.html { redirect_to @todolist, notice: 'Todolist was successfully updated.' }
        format.json { render :show, status: :ok, location: @todolist }
      else
        format.html { render :edit }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todolists/1
  # DELETE /todolists/1.json
  def destroy
    @todolist.destroy
    respond_to do |format|
      format.html { redirect_to todolists_url, notice: 'Todolist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Custom methods

  def addtasks
    @id = params[:id]
    @todolist = Todolist.find(@id)
    gon.tasks = @todolist.tlitems.with_task
    gon.tlitems_path = tlitems_path
    gon.getoutlist_tasks_path = getoutlist_tasks_path
    gon.todlist = @todolist
  end

  def getbydate
    @todolist = current_user.todolists.find_by(date: params[:date])
    if @todolist
      render json: @todolist.tasks
    else
      render json: nil
    end
  end

  def findbydate
    @todolist = current_user.todolists.find_by(date: params[:date])
    redirect_to addtasks_todolist_path(@todolist.id) and return
  end

  # End custom methods

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todolist
      @todolist = Todolist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todolist_params
      params.require(:todolist).permit(:date, :notes, :result)
    end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tlitems_helper.rb
module TlitemsHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/todolists/_form.html.haml
= form_for(@todolist) do |f|
  - if @todolist.errors.any?
    #error_explanation
      %h2
        = pluralize(@todolist.errors.count, "error")
        prohibited this todolist from being saved:
      %ul
        - @todolist.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :date
    %br/
    .input-group.date
      = f.text_field :date, class: 'datepicker'
  .field
    = f.label :notes
    %br/
    = f.text_area :notes
  .field
    = f.label :result
    %br/
    = f.text_field :result
  .actions
    = f.submit

app/views/todolists/addtasks.html.haml
.row
  .col-lg-5
    .row
      .col-md-12
        .panel.tasks-widget
          .panel-heading
            %h3#navbar TodoList
          .panel-body
            .task-content
              %ul#sortable.task-list

  .col-lg-1   
    %span.token-box-icon.disable{:colordata => 'purple', :tokenname => 'ticket'}
      %i.ion.ion-pricetag
      %span.count-asig 2
    %span.token-box-icon.disable{:colordata => 'red', :tokenname => 'tshirt'}
      %i.ion.ion-tshirt
      %span.count-asig 6
    %span.token-box-icon.disable{:colordata => 'green', :tokenname => 'money'}
      %i.ion.ion-cash
      %span.count-asig 4
    %span.token-box-icon.disable{:colordata => 'yellow', :tokenname => 'school'}
      %i.ion.ion-university
      %span.count-asig 3
    %span.addtoken.bg-green
      %i.ion.ion-arrow-down-b
  .col-lg-6   
    .row
      .col-md-12
        .panel.tasks-widget
          .panel-heading
            %h3#navbar Tasks
            .panel-tools.pull-right
              .btn-group
                %button.btn.btn-info.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown"}
                  Select Type Task
                  %span.caret
                %ul.dropdown-menu
                  %li
                    %a#new-task-button{:href => "javascript:void(0)"} New
                  %li
                    %a#pending-task-button{:href => "javascript:void(0)"} Pending
                  %li.divider
                  %li
                    %a{:href => "#"} Proyecto 1
                  %li
                    %a{:href => "#"} Proyecto 2
                  %li
                    %a{:href => "#"} Proyecto 3
          .panel-body
            %form#task-form.form-horizontal{ :method => 'POST', :action => tlitems_path}
              %fieldset

              %input{:name => request_forgery_protection_token.to_s, :type => "hidden", :value => form_authenticity_token}/
              %input{:name => "todolist_id", :type => "hidden", :value => @id}/
              %input{:name => "task[status]", :type => "hidden", :value => "inlist"}
              .form-group
                %label.col-lg-3.control-label{:for => "task_title"} Title
                .col-lg-9
                  %input.form-control#task_title{:name => "task[title]", :type => "text"}/
              .form-group
                %label.col-lg-3.control-label{:for => "task_description"} Description
                .col-lg-9
                  %input#task_description.form-control{:name => "task[description]", :type => "text"}/
              .form-group
                %label.col-lg-3.control-label{:for => "task_rank"} Rank
                .col-lg-9
                  %input#task_rank.form-control{:name => "task[rank]", :type => "number"}/
              .form-group
                .col-lg-9.col-lg-offset-3
                  %input#submit-task.btn.btn-primary{:name => "commit", :type => "button", :value => "Add Task"}/
            #ready-task-contend.task-content{:style =>"display: none;"}
              %ul#ready-tasks.task-list
        

- content_for :custom_js do
  = javascript_include_tag 'addtasks'

app/views/todolists/edit.html.erb
<h1>Editing Todolist</h1>

<%= render 'form' %>

<%= link_to 'Show', @todolist %> |
<%= link_to 'Back', todolists_path %>

app/views/todolists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todolists</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Notes</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todolists.each do |todolist| %>
      <tr>
        <td><%= todolist.date %></td>
        <td><%= todolist.notes %></td>
        <td><%= todolist.result %></td>
        <td><%= link_to 'Show', todolist %></td>
        <td><%= link_to 'Edit', edit_todolist_path(todolist) %></td>
        <td><%= link_to 'Destroy', todolist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todolist', new_todolist_path %>

app/views/todolists/new.html.erb
<h1>New Todolist</h1>

<%= render 'form' %>

<%= link_to 'Back', todolists_path %>

app/views/todolists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @todolist.date %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @todolist.notes %>
</p>

<p>
  <strong>Result:</strong>
  <%= @todolist.result %>
</p>

<%= link_to 'Edit', edit_todolist_path(@todolist) %> |
<%= link_to 'Back', todolists_path %>